#######################################################
#
#	selectAssociatedGenes.R
#	SELECTS GENES NEAR TO X MB OF A SNP ASSOCIATED
#	WITH A DETERMINED PHENOTYPE.
#
#	AUTHOR. JAVIER MONTALVO-ARREDONDO.
#	VERSION. 0
#	CONTACT. buitrejma[at]gmail[dot]com
#	CALZADA ANTONIO NARRO, 1923,
#	SAN BUENAVISTA SALTILLO COAHUILA, C.P. 25315
#
#	TAKES THE GWAS ANALYSIS RESULTS TABLE, A TRANSCRIPTOME ANNOTATION
#	FILE IN GFF FORMAT AND A HEADER HASH TABLE RELATING CHROMOSOME
#	NAME AND NUMBER OF CHROMOSOME. THIS CODE WILL SELECT GENES NEAR 
#	TO A SIGNIFICATIVE SNP ASSOCIATED WITH PHENOTYPE.
#
#
#	PSEUDO-CODE.
#	
#	10	DECLARE XMB AS INT: NUMBER IN MEGABASES TO SEARCH GENES NEAR TO THE SIGNIFICATIVE SNP
#	15	DECLARE PROD_CONTAINER AS DATAFRAME:
#	20	WITH INPUT FILES CREATE DATA OBJECTS (OBJECT-GWAS-RESULTS, OBJECT-HEADER-HASH, OBJECT-GFF).
#	30	ITERATE AMONG OBJECT-GWAS-RESULTS ROWS.
#	3010		LET NAME  TAKES OBJECT-GWAS-RESULTS$SNP_ID.
#	3020		LET CHRN  TAKES CHROMOSOME_NAME FROM OBJECT-HEADER-HASH USING OBJECT-GWAS-RESULTS$CHR_NUMBER AS A KEY.
#	3030		LET POS   TAKES OBJECT-GWAS-RESULTS$SNP_POSITION.
#	3040		LET START TAKES CALCULATION OF POS - XMB.
#	3050		LET END   TAKES CALCULATION OF POS + XMB.
#	3060		SAMPLE OBJECT-GFF BY CHRN
#	3070		LET PROD  TAKES OBJECT-GFF$PRODUCT IF [OBJECT-GFF$START >= START & OBJECT-GFF$END <= END] OR DO CONTINUE
#	3075		LET NAME, CHRN, POS BE THE SAME LENGTH OF A PROD COLUMN.
#	3080		LET PROD_CONTAINER CBINDS NAME, CHRN, POS, PROD.
#	40	RETURN PROD_CONTAINER
############################################################



